server:
  port: 9201
service-url:
  user-service: http://localhost:8101

spring:
  cloud:
    gateway:
      routes:
        - id: add_request_parameter_route
          uri: ${service-url.user-service}
          filters:
            - AddRequestParameter=username, jourwon
          predicates:
            - Path=/user/**
