# 指定运行端口
server:
  port: 8102

# 指定服务名称
spring:
  application:
    # 当做服务名称,不区分大小写
    name: user-service

eureka:
#  instance:
     # 配置使用主机名注册服务 
#    hostname: localhost
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    service-url:
      # 配置注册中心地址
      defaultZone: http://localhost:8001/eureka