server:
  port: 8306

spring:
  application:
    name: consul-ribbon-service
  cloud:
    consul:
      # 将服务注册到consul
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        
service-url:
  # 配置服务，用于restTemplate调用，其中：
  # http://表示使用http协议，
  # USER-SERVICE为user-service项目配置在yml中的应用名，即注册中心中的Application名（不区分大小写），用于服务发现
  consul-user-service: http://consul-user-service