# 指定运行端口
server:
  port: 8107

# 指定服务名称
spring:
  application:
    # 当做服务名称,不区分大小写
    name: consul-user-service
  cloud:
    consul:
      # 将服务注册到consul
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}