server:
  port: 9305

spring:
  application:
    name: admin-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 添加开启admin的日志监控
logging:
  file:
    path: /log
    name: admin-client.log