server:
  port: 8301

spring:
  application:
    name: ribbon-service
  zipkin:
    base-url: http://192.168.2.121:9411
   #设置Sleuth的抽样收集概率
  sleuth:
    sampler:
      probability: 0.1


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/


service-url:
  # 配置服务，用于restTemplate调用，其中：
  # http://表示使用http协议，
  # USER-SERVICE为user-service项目配置在yml中的应用名，即注册中心中的Application名（不区分大小写），用于服务发现
  user-service: http://user-service